name    	'puppet-mongodb'
version 	'1.0.0'
source 		'Github'
author 		'Jan Collijs'
license 	'GPL'
summary 	'This module manages the mongodb service'
description 	'Using this module ensures the mongodb service will be maintained'
project_page 	'https://github.com/visibilityspots/puppet-mongodb'
